export const DAILYREPORTDATA = [
  {
    username: "C Ronaldo",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Erik Haag",
    userId: "5636R36T36",
    sunday: "No Activity",
    monday: "Logged In",
    tuesday: "Created Bubble",
    wednesday: "Created Comment",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Danny Wellbeck",
    userId: "5636R36T36",
    sunday: "Created Bubble",
    monday: "No Activity",
    tuesday: "Created Comment",
    wednesday: "No Activity",
    thursday: "Created Bubble",
    friday: "Logged In",
    saturday: "No Activity",
  },
  {
    username: "Skepta Adenuga",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "J Basquiat",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "Created Bubble",
    tuesday: "No Activity",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Virgil Abloh",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Comment",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Sam Altman",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Elon Musk",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Gretha Thunberg",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Comment",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Daniel Park",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Tyson Fury",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Comment",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
];

export const DAILYREPORTSUMMARYDATA = [
  {
    username: "C Ronaldo",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Erik Haag",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Danny Wellbeck",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Skepta Adenuga",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "J Basquiat",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Virgil Abloh",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Sam Altman",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Elon Musk",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Gretha Thunberg",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Daniel Park",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
  {
    username: "Tyson Fury",
    days_since_onboarding: "4",
    logged_in: "4",
    created_bubble: "4",
    created_comment: "4",
    no_activity: "--",
  },
];

export const GROUPREPORTDATA = [
  {
    username: "-------",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Earshot",
    userId: "5636R36T36",
    sunday: "No Activity",
    monday: "Logged In",
    tuesday: "Created Bubble",
    wednesday: "Created Comment",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Evenings",
    userId: "5636R36T36",
    sunday: "Created Bubble",
    monday: "No Activity",
    tuesday: "Created Comment",
    wednesday: "No Activity",
    thursday: "Created Bubble",
    friday: "Logged In",
    saturday: "No Activity",
  },
  {
    username: "No Signal",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Spring Agency",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "Created Bubble",
    tuesday: "No Activity",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Bayy Agency",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Comment",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Mother (NYC A)",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Blooming Dales",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Not Yet Mad",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Comment",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Zynga",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Bubble",
    wednesday: "Created Bubble",
    thursday: "Created Bubble",
    friday: "No Activity",
    saturday: "No Activity",
  },
  {
    username: "Interact",
    userId: "5636R36T36",
    sunday: "Logged In",
    monday: "No Activity",
    tuesday: "Created Comment",
    wednesday: "Created Bubble",
    thursday: "Created Comment",
    friday: "No Activity",
    saturday: "No Activity",
  },
];

export const WAITLISTDATA = [
  {
    name: "John Doe",
    number: "08012345678",
    city: "Lagos",
    creativeWork: "Art",
    teamSize: "2-5",
    messenger: "WhatsApp",
    messengerFeelings: "Happy",
    sharingFrequency: "Daily",
    fitScore: "80%",
    dateJoined: "12th May, 2021",
  },
  {
    name: "Jane Doe",
    number: "08012345678",
    city: "Lagos",
    creativeWork: "Art",
    teamSize: "2-5",
    messenger: "WhatsApp",
    messengerFeelings: "Happy",
    sharingFrequency: "Daily",
    fitScore: "80%",
    dateJoined: "12th May, 2021",
  },
  {
    name: "John Doe",
    number: "08012345678",
    city: "Lagos",
    creativeWork: "Art",
    teamSize: "2-5",
    messenger: "WhatsApp",
    messengerFeelings: "Happy",
    sharingFrequency: "Daily",
    fitScore: "80%",
    dateJoined: "12th May, 2021",
  },
  {
    name: "John Doe",
    number: "08012345678",
    city: "Lagos",
    creativeWork: "Art",
    teamSize: "2-5",
    messenger: "WhatsApp",
    messengerFeelings: "Happy",
    sharingFrequency: "Daily",
    fitScore: "80%",
    dateJoined: "12th May, 2021",
  },
  {
    name: "John Doe",
    number: "08012345678",
    city: "Lagos",
    creativeWork: "Art",
    teamSize: "2-5",
    messenger: "WhatsApp",
    messengerFeelings: "Happy",
    sharingFrequency: "Daily",
    fitScore: "80%",
    dateJoined: "12th May, 2021",
  },
  {
    name: "John Doe",
    number: "08012345678",
    city: "Lagos",
    creativeWork: "Art",
    teamSize: "2-5",
    messenger: "WhatsApp",
    messengerFeelings: "Happy",
    sharingFrequency: "Daily",
    fitScore: "80%",
    dateJoined: "12th May, 2021",
  },
];
